// ESLint configuration for jQuery-based frontend
export default [
    {
        files: ["js/**/*.js"],
        ignores: ["js/jquery/**/*.js"], // Ignore minified jQuery library
        languageOptions: {
            ecmaVersion: 2015,
            sourceType: "script",
            globals: {
                // Browser globals
                window: "readonly",
                document: "readonly",
                console: "readonly",
                alert: "readonly",
                confirm: "readonly",
                setTimeout: "readonly",
                setInterval: "readonly",
                clearTimeout: "readonly",
                clearInterval: "readonly",
                // jQuery
                $: "readonly",
                jQuery: "readonly",
                // Common APIs
                XMLHttpRequest: "readonly",
                FormData: "readonly",
                localStorage: "readonly",
                sessionStorage: "readonly",
                location: "readonly",
                history: "readonly",
                navigator: "readonly",
                // External libraries
                StripeCheckout: "readonly",
                // Application global variables (defined in index-0.0.2.js)
                env_vars: "writable",
                csrftoken: "writable",
                terms_of_use_version: "writable",
                mb_cd: "writable",
                pr_cd: "writable",
                em_cd: "writable",
                ad_cd: "writable",
                member_first_name: "writable",
                member_last_name: "writable",
                member_email_address: "writable",
                chat_dialogue_name_field: "writable",
                chat_dialogue_email_address_field: "writable",
                chat_dialogue_message_field: "writable",
                chat_dialogue_name_error: "writable",
                chat_dialogue_email_address_error: "writable",
                chat_dialogue_message_error: "writable",
                // Global functions (multi-file architecture)
                // Note: This architecture uses global functions across files
                // Future refactoring could modularize this into ES6 modules
                post_header: "writable",
                set_logged_in: "writable",
                logout_successful: "writable",
                load_account: "writable",
                load_token: "writable",
                verify_email_address: "writable",
                verify_email_address_response: "writable",
                verify_email_address_callback: "writable",
                verify_email_address_response_callback: "writable",
                display_payment_data: "writable",
                set_up_stripe_checkout_handler: "writable",
                stripe_checkout_handler_token_callback: "writable",
                process_stripe_payment_token: "writable",
                process_stripe_payment_token_callback: "writable",
                change_my_password: "writable",
                change_my_password_callback: "writable",
                set_up_change_my_password_form_listeners: "writable",
                update_communication_preferences: "writable",
                update_communication_preferences_callback: "writable",
                set_up_edit_communication_preferences_form_listeners: "writable",
                update_my_information: "writable",
                update_my_information_callback: "writable",
                set_up_edit_my_information_form_listeners: "writable",
                check_if_reason_selected: "writable",
                email_unsubscribe_confirm: "writable",
                email_unsubscribe_confirm_callback: "writable",
                email_unsubscribe_why: "writable",
                email_unsubscribe_why_callback: "writable",
                load_email_unsubscribe: "writable",
                set_up_email_unsubscribe_form_listeners: "writable",
                load_order: "writable",
                ajax_error: "writable",
                cart_check_for_valid_checkout_conditions: "writable",
                cart_delete_cart: "writable",
                cart_delete_cart_callback: "writable",
                cart_remove_sku: "writable",
                cart_remove_sku_callback: "writable",
                cart_update_shipping_method: "writable",
                cart_update_shipping_method_callback: "writable",
                cart_update_sku_quantity_callback: "writable",
                load_cart_items: "writable",
                load_cart_totals: "writable",
                load_shipping_methods_details: "writable",
                set_up_cart_form_listeners: "writable",
                show_empty_cart: "writable",
                update_cart_contains_backordered_out_of_stock_item: "writable",
                update_cart_item_quantity: "writable",
                update_sku_quantity: "writable",
                change_confirmation_email_address: "writable",
                change_confirmation_email_address_callback: "writable",
                check_if_checkout_ready: "writable",
                checkout_allowed_callback: "writable",
                confirm_order_terms_of_sale_agree_changed: "writable",
                confirm_place_order: "writable",
                confirm_place_order_callback: "writable",
                load_confirm_items: "writable",
                load_confirm_payment_data: "writable",
                load_confirm_totals: "writable",
                look_up_anonymous_email_address: "writable",
                look_up_anonymous_email_address_callback: "writable",
                set_up_confirm_form_listeners: "writable",
                create_account: "writable",
                create_account_success: "writable",
                set_up_create_account_form_listeners: "writable",
                forgot_username: "writable",
                forgot_username_callback: "writable",
                set_up_forgot_username_form_listeners: "writable",
                check_termsofserviceisagreed_member_success: "writable",
                member_terms_and_conditions_agree_action: "writable",
                member_terms_and_conditions_agree_action_success: "writable",
                submit_chat_message: "writable",
                submit_chat_message_success: "writable",
                login_success: "writable",
                set_up_login_form_listeners: "writable",
                change_displayed_image: "writable",
                error_product_add_to_cart: "writable",
                hide_image_modal: "writable",
                load_product: "writable",
                product_add_to_cart: "writable",
                product_add_to_cart_callback: "writable",
                set_up_product_form_listeners: "writable",
                show_hide_inventory_status_help: "writable",
                show_image_modal: "writable",
                sku_radio_description_clicked: "writable",
                sku_radio_item_changed: "writable",
                sku_radio_item_clicked: "writable",
                success_product_add_to_cart: "writable",
                load_products: "writable",
                pythonabot_notify_me_callback: "writable",
                set_up_pythonabot_form_listeners: "writable",
                submit_pythonabot_coming_soon: "writable",
                reset_password: "writable",
                reset_password_callback: "writable",
                set_up_reset_password_form_listeners: "writable",
                reset_submit_button: "writable",
                set_new_password: "writable",
                set_new_password_callback: "writable",
                set_up_set_new_password_form_listeners: "writable",
                // Additional cross-file function dependencies
                load_shipping_methods: "writable",
                load_confirm_shipping_methods: "writable"
            }
        },
        rules: {
            // Best practices
            "no-unused-vars": ["warn", { "args": "none" }], // Allow unused function parameters (common in callbacks)
            "no-undef": "error",
            "no-console": "off", // Allow console for now
            "no-debugger": "warn",

            // Style
            "semi": ["warn", "always"],
            "quotes": ["warn", "single", { "avoidEscape": true }],
            "indent": ["warn", 4],

            // Potential errors
            "no-unreachable": "error",
            "no-dupe-keys": "error",
            "no-duplicate-case": "error"
        }
    }
];
